name: Build and Test

on:
  pull_request:
    types: [opened, reopened, closed, synchronize, ready_for_review]

  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  build-and-test:
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.draft == false || 
      github.event_name == 'pull_request' && github.event.pull_request.merged == true ||
      github.event_name == 'push' && github.ref == 'refs/heads/main'
      github.event_name == 'push' && startsWith(github.ref, 'refs/heads/releases/')

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build API
      run: dotnet build EmployeeManagement/EmployeeManagement.csproj --no-restore
    - name: Run unit tests
      run: dotnet test EmployeeManagement.Test/EmployeeManagement.Test.csproj --logger "trx;LogFileName=test-results.trx"
